name: solar-system-ci

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
      MONGO_USER: 'superuser'
      MONGO_PASSWORD: 'SuperPassword'

    steps:
      - name: Checkout repository  
        uses: actions/checkout@v5

      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  